security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user, roles:  [ROLE_ADMIN,ROLE_USER]}
        - { path: ^/api/admin, roles: ROLE_ADMIN}